### PR TITLE
Editor fly controls

### PR DESCRIPTION
**Pull request by jmickle66666666**
Small modification to the camera controls in delvedit so you fly at the camera direction, matching standard 3d view fly controls.

Also includes my vscode tasks.json for running and building the engine, let me know if I should remove them first.

### CODE REVIEW

**Comment by joshuaskelly** [comment]
We probably should pull the VSCode IDE artifacts? Currently the blessed way is IntelliJ.

**Comment by jmickle66666666** [comment]
Done!

**Comment by Interrupt** [comment]
Looks good! Just see one issue: I'm noticing that when facing directly into the red axis (+X -X?) that the camera height overshoots what the camera is pointing at.

**Comment by jmickle66666666** [comment]
Fixed! Should be correct now

**Comment by Interrupt** [comment]
Thanks for this!

**Pull request merged**
