### PR TITLE
Features/example art techpack

### PR DESCRIPTION
**Pull request by Interrupt**
This updates the example level with a new theme, updated splash level and updated example level. Tried to do a better job of showing off the engine features, and drawing attention to their use.

Delver Engine 9_17_2020 12_33_50 AM

Delver Engine 9_17_2020 12_32_54 AM

delver-engine-new-splash

### CODE REVIEW

**Comment by joshuaskelly** [comment]
image
Is there supposed to be a dialogue trigger here?

**Comment by joshuaskelly** [comment]
image
These tiles aren't animating.

**Review by joshuaskelly — CHANGES_REQUESTED** [review]
I've posted two comments with screenshots. Is the text incorrect, or are the features they are highlighting not working?

**Comment by Interrupt** [comment]
> 
> 
> image
> Is there supposed to be a dialogue trigger here?

Maybe I should rename that to 'Message Trigger' instead of 'Dialogue Trigger'

**Comment by Interrupt** [comment]
Updated the level with some more Triggers, making the 'Dialog Trigger' area a more general 'Triggers' area

**Review by joshuaskelly — APPROVED** [review]
Looks good to me!

**Pull request merged**
